# Generated by Django 5.1.4 on 2025-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_evaluation_unique_together_favoriteservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='clients_served',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
