# Generated by Django 5.1.4 on 2025-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_provider_clients_served_provider_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
